version : "3"
services:
  ditto-server:
    image: liyangwood/dittobox:1.0.0
    container_name: ditto-server
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./data/ditto:/mnt/data
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=111111